# Generated by Django 4.2.23 on 2025-07-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_units_alter_profile_current_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Provide description about yourself and your fitness goals.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_weight',
            field=models.PositiveIntegerField(default=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default='male', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='units',
            field=models.PositiveIntegerField(choices=[(1, 'kg'), (2, 'lbs')], default=1),
        ),
    ]
