# Generated by Django 4.2.23 on 2025-07-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_remove_workouts_content_workouts_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='description',
            field=models.CharField(default='Enter Short Description', max_length=200),
        ),
    ]
