# Generated by Django 4.2.23 on 2025-07-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_workouts_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouts',
            name='user',
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
