# Generated by Django 4.2.23 on 2025-07-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_remove_workouts_user_exercise_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='training_style',
            field=models.CharField(choices=[('straightsets', 'STRAIGHTSETS'), ('dropsets', 'DROPSETS'), ('clustersets', 'CLUSTERSETS'), ('pyramidsets', 'PYRAMIDsets'), ('timeundertension', 'TIMEUNDERTENSION'), ('other', 'OTHER')], default='split', max_length=50),
        ),
        migrations.AddField(
            model_name='exercise',
            name='units',
            field=models.CharField(default='kg or lbs'),
        ),
        migrations.AddField(
            model_name='workouts',
            name='training_split',
            field=models.CharField(default='Enter Split', max_length=200),
        ),
    ]
