# Generated by Django 4.2.23 on 2025-07-22 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_exercise_training_style_exercise_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='training_style',
            field=models.CharField(choices=[('straightsets', 'STRAIGHTSETS'), ('dropsets', 'DROPSETS'), ('clustersets', 'CLUSTERSETS'), ('pyramidsets', 'PYRAMIDSETS'), ('timeundertension', 'TIMEUNDERTENSION'), ('other', 'OTHER')], default='split', max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workouts'),
        ),
    ]
