# Generated by Django 4.2.23 on 2025-07-26 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0006_alter_exercise_training_style_alter_exercise_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='units',
            field=models.CharField(choices=[('kg', 'KILOGRAMS'), ('lbs', 'POUNDS')], default='kg or lbs'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workouts'),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='description',
            field=models.TextField(blank=True, default='Enter Short Description'),
        ),
        migrations.CreateModel(
            name='WorkoutDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('workout_duration', models.PositiveIntegerField(blank=True, default='Duration in Minutes', null=True)),
                ('notes', models.CharField(max_length=100)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workouts')),
            ],
        ),
    ]
