# Generated by Django 4.2.23 on 2025-08-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_alter_exercise_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='training_split',
            field=models.CharField(default='e.g Upper Body, Lower Body , PPL', max_length=200),
        ),
    ]
