# Generated by Django 4.2.23 on 2025-08-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_alter_workouts_training_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
