# Generated by Django 4.2.23 on 2025-08-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0011_exercise_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='units',
            field=models.CharField(choices=[('kg', 'KILOGRAMS'), ('lbs', 'POUNDS')], default='kg or lbs', max_length=20),
        ),
    ]
