# Generated by Django 4.2.23 on 2025-08-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_alter_exercise_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='training_style',
            field=models.CharField(choices=[('straightsets', 'STRAIGHTSETS'), ('dropsets', 'DROPSETS'), ('clustersets', 'CLUSTERSETS'), ('pyramidsets', 'PYRAMIDSETS'), ('timeundertension', 'TIMEUNDERTENSION'), ('other', 'OTHER')], default='straightsets', max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='units',
            field=models.CharField(choices=[('kg', 'KILOGRAMS'), ('lbs', 'POUNDS')], default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='training_split',
            field=models.CharField(default='e.g Upper Body, Lower Body, PPL', max_length=200),
        ),
    ]
